---
title: "Lab2"
author: "K Iwasaki"
date: "June 28, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Problem 3 - same calculation by computation to the manual calculation

```{r}

# uniform distribution [0, 1]
base <- seq(0, 1, 0.001)
length(base)
p.base <- rep(1/1001, 1001)

# r.v. a1 and a2 with the uniform distribution
a1 <- sample(base, size = 100000, prob = p.base, replace = T)
a2 <- sample(base, size = 100000, prob = p.base, replace = T)

# create a dataframe and store X, Y within the dataframe
samples <- data.frame(a1, a2)
samples$x <- ifelse(samples$a1 > samples$a2, samples$a1, samples$a2)
samples$y <- ifelse(samples$a1 > samples$a2, samples$a2, samples$a1)

# calculate xy
samples$xy <- samples$x * samples$y

plot(samples$x, samples$y, 
     main = "The region for which X and Y have positive probability density",
     xlab = "X",
     ylab = "Y")


(e.x <- mean(samples$x))
(e.y <- mean(samples$y))
(e.xy <- mean(samples$xy))
cov(samples$x, samples$y)


```


## Problem 4
### e. n = 100, plot X, Y and cacluate D1, D2, ,,,Dn

```{r}
# uniform distribution [-1, 1]
base <- seq(-1, 1, 0.01)
p.base <- rep(1/length(base), length(base))

# r.v. X and Y with the uniform distribution
x.values <- sample(base, size = 100, prob = p.base, replace = T)
y.values <- sample(base, size = 100, prob = p.base, replace = T)

# create a dataframe and store the X, Y
samples <- data.frame(x.values, y.values)
samples$xy <- samples$x.values^2 + samples$y.values^2

# compute D
samples$d.values <- 0
samples$d.values[samples$xy < 1] <- 1

plot(samples$x.values, samples$y.values, col=samples$d.values+1, asp=1)

```
### f. calculate sample average and compare to the answer for part a

```{r}
mean(samples$d.values)
# this is very close the answer for part a: pi/4=0.7853

```


### g. replicate this 10,000 times

```{r}

# store the mean each time
samples.trials <- c()
for (i in 1:10000) {
  x.values <- sample(base, size = 100, prob = p.base, replace = T)
  y.values <- sample(base, size = 100, prob = p.base, replace = T)
  
  samples <- data.frame(x.values, y.values)
  samples$xy <- samples$x.values^2 + samples$y.values^2
  samples$d.values <- 0
  samples$d.values[samples$xy < 1] <- 1
  samples.trials[i] = mean(samples$d.values)
}

mean(samples.trials)

# plot the histogram of the sample means
hist(samples.trials, breaks = 20)

```

#h. calcualte the standard deviation of the sample mean

```{r}
sd(samples.trials)
# this is close the caculation for part c: 0.04105458
```



#i. calculate the fraction of samples averages that are larger than 3/4
```{r}
sum(sapply(samples.trials, function(x) {ifelse( x > 3/4, 1, 0)}))/10000
# this is not so close the sample mean calculated in part d which is 0.8057173

```



